{ SPDX-License-Identifier: Apache-2.0                                   }
{ Copyright (c) 2026 George Saliba <george.saliba@salitronic.com>                                      }
{
  Cross-validation Pascal program.

  Reads test cases from cross_validate_inputs.txt (generated by Python),
  runs each through the REAL Pascal function (copied from Main.pas / Utils.pas),
  writes results to cross_validate_outputs.txt.

  The Python test then compares Pascal outputs against Python reimplementation
  outputs to prove they are identical.

  Protocol:
    Input:  FUNCTION_NAME<TAB>base64(arg1)<TAB>base64(arg2)<TAB>...
    Output: base64(result)   (one per line, matching input order)

  Compile (adjust -Fu to point at your FPC fcl-base unit path; on many
  installs fpc.cfg already has this and plain `fpc` works):
    fpc -Fu<path-to-fpc>/units/i386-win32/fcl-base cross_validate_pascal.pas
  Run:
    cross_validate_pascal.exe <input_file> <output_file>
}
program cross_validate_pascal;

{$mode delphi}

uses
  SysUtils, Classes, base64;

{ ========================================================================= }
{ Functions under test - EXACT copies from Main.pas and Utils.pas            }
{ ========================================================================= }

{ --- From Utils.pas --- }

function MilsToCoord(Mils : Integer) : Integer;
begin
  Result := Mils * 10000;
end;

function CoordToMils(Coord : Integer) : Integer;
begin
  Result := Round(Coord / 10000);
end;

function MMToCoord(MM : Double) : Integer;
begin
  Result := Round(MM * 10000000 / 25.4);
end;

function CoordToMM(Coord : Integer) : Double;
begin
  Result := Coord * 25.4 / 10000000;
end;

function BoolToJsonStr(Value : Boolean) : String;
begin
  if Value then Result := 'true'
  else Result := 'false';
end;

function StrToBoolCustom(S : String) : Boolean;
begin
  Result := (LowerCase(S) = 'true') or (S = '1');
end;

function StrToIntDefCustom(S : String; Default : Integer) : Integer;
begin
  if (S = '') or (S = 'null') then
    Result := Default
  else
  begin
    try
      Result := StrToInt(S);
    except
      Result := Default;
    end;
  end;
end;

{ --- From Utils.pas, verbatim. tests/test_locale_decimal.py fails if  }
{ these drift. Replaced a hand-written StrToFloatDefCustom that shared }
{ only the NAME with the real function and had none of its guards.     }
Function IsFloatStr(S : String) : Boolean;
Var
    I, StartPos : Integer;
    Dots, Digits, Exponents : Integer;
    Ch : String;
Begin
    S := Trim(S);
    Result := False;
    If S = '' Then Exit;
    StartPos := 1;
    If (S[1] = '-') Or (S[1] = '+') Then StartPos := 2;
    If StartPos > Length(S) Then Exit;

    Dots := 0;
    Digits := 0;
    Exponents := 0;
    For I := StartPos To Length(S) Do
    Begin
        Ch := Copy(S, I, 1);
        If (Ch >= '0') And (Ch <= '9') Then
            Digits := Digits + 1
        Else If Ch = '.' Then
        Begin
            Dots := Dots + 1;
            If Dots > 1 Then Exit;
            If Exponents > 0 Then Exit;   { 1e5.5 is not a number }
        End
        Else If (Ch = 'e') Or (Ch = 'E') Then
        Begin
            Exponents := Exponents + 1;
            If Exponents > 1 Then Exit;
            If Digits = 0 Then Exit;      { 'e5' has no mantissa }
            { A sign may follow the exponent, and a digit must. }
            If I = Length(S) Then Exit;
            Ch := Copy(S, I + 1, 1);
            If (Ch = '-') Or (Ch = '+') Then
            Begin
                If I + 1 = Length(S) Then Exit;
                Ch := Copy(S, I + 2, 1);
            End;
            If (Ch < '0') Or (Ch > '9') Then Exit;
        End
        Else
            Exit;                          { anything else is not a number }
    End;
    Result := Digits > 0;
End;

Function FloatToJsonStr(Value : Double) : String;
Var
    Sep, Ch, Swapped : String;
    I : Integer;
Begin
    { Locale-agnostic float -> string. Delphi FloatToStr respects the global
      DecimalSeparator, so on a comma-decimal system it produces '90,0',
      which is not valid JSON.

      NO GLOBAL IS MUTATED. This used to set DecimalSeparator to '.' for the
      duration of the call and restore it after. That works, but it leaves a
      window in which a global the whole application shares has been changed
      underneath it, and the window gets wider every time another call site
      starts using this wrapper. Converting first and swapping the separator
      character afterwards has no window at all.

      Swapping is complete because FloatToStr emits only digits, a sign, an
      exponent 'E' and the single decimal separator. It never emits a
      thousands separator, which is FloatToStrF with ffNumber. }
    Result := FloatToStr(Value);
    Sep := DecimalSeparator;
    If Sep <> '.' Then
    Begin
        Swapped := '';
        For I := 1 To Length(Result) Do
        Begin
            Ch := Copy(Result, I, 1);
            If Ch = Sep Then Ch := '.';
            Swapped := Swapped + Ch;
        End;
        Result := Swapped;
    End;
End;

Function StrToFloatDef(S : String; Default : Double) : Double;
Var
    Sep, Ch, Work : String;
    I : Integer;
Begin
    { Locale-agnostic float parsing. JSON always uses '.' as the decimal      }
    { separator regardless of the user's Windows regional settings, but Delphi}
    { StrToFloat respects the global DecimalSeparator, so on a system with    }
    { comma-as-decimal (much of Europe) parsing "90.0" silently fails and     }
    { the default value comes back instead. The string is reshaped into the   }
    { form THIS locale parses and the global is never touched; forcing the    }
    { separator and restoring it was the earlier approach and is now          }
    { forbidden by test_the_wrappers_do_not_mutate_the_global_separator.      }
    If (S = '') Or (S = 'null') Then
    Begin
        Result := Default;
        Exit;
    End;
    { PRE-CHECKED, not merely guarded. The Try/Except below cannot save
      the session: the script IDE breaks on the exception before the
      handler runs, so a value like 'abc' halts on the StrToFloat line
      behind an EConvertError dialog and the polling loop stops with it.
      StrToIntDef has carried this pre-check for the same reason. }
    If Not IsFloatStr(S) Then
    Begin
        Result := Default;
        Exit;
    End;

    { IsFloatStr above guarantees S is in dot form, so the conversion is
      done by putting it into the form THIS locale parses rather than by
      forcing the locale to match the string. Same reasoning as the emit
      side: no global is touched, so there is no window.

      The Try/Except is kept as a backstop and should now be unreachable:
      a pre-validated, locale-formed string does not raise EConvertError.
      It is deliberately not relied on, because the script engine surfaces
      an RTL conversion error as a modal before the handler runs. }
    Sep := DecimalSeparator;
    Work := S;
    If Sep <> '.' Then
    Begin
        Work := '';
        For I := 1 To Length(S) Do
        Begin
            Ch := Copy(S, I, 1);
            If Ch = '.' Then Ch := Sep;
            Work := Work + Ch;
        End;
    End;

    Try
        Result := StrToFloat(Work);
    Except
        Result := Default;
    End;
End;

function EscapeJsonString(S : String) : String;
begin
  Result := S;
  Result := StringReplace(Result, '\', '\\', [rfReplaceAll]);
  Result := StringReplace(Result, '"', '\"', [rfReplaceAll]);
  Result := StringReplace(Result, #13, '\r', [rfReplaceAll]);
  Result := StringReplace(Result, #10, '\n', [rfReplaceAll]);
  Result := StringReplace(Result, #9, '\t', [rfReplaceAll]);
end;

{ --- Property store: "Name=Value|Name=Value|..." --- }
{ Used as a stand-in for ISch_GraphicalObject property access.            }
{ Encodes the parsing/construction logic of MatchesFilter/BuildObjectJson  }
{ /ApplySetProperties WITHOUT depending on Altium API types.              }

function GetStoredProperty(PropStore : String; Name : String) : String;
var
  Remaining, Entry, EntryName, EntryValue : String;
  PipePos, EqPos : Integer;
begin
  Result := '';
  Remaining := PropStore;
  while Remaining <> '' do
  begin
    PipePos := Pos('|', Remaining);
    if PipePos > 0 then
    begin
      Entry := Copy(Remaining, 1, PipePos - 1);
      Remaining := Copy(Remaining, PipePos + 1, Length(Remaining));
    end
    else
    begin
      Entry := Remaining;
      Remaining := '';
    end;

    EqPos := Pos('=', Entry);
    if EqPos = 0 then Continue;
    EntryName := Copy(Entry, 1, EqPos - 1);
    EntryValue := Copy(Entry, EqPos + 1, Length(Entry));

    if EntryName = Name then
    begin
      Result := EntryValue;
      Exit;
    end;
  end;
end;

function SetStoredProperty(PropStore : String; Name : String; Value : String) : String;
var
  Remaining, Entry, EntryName : String;
  PipePos, EqPos : Integer;
  Found : Boolean;
begin
  Result := '';
  Remaining := PropStore;
  Found := False;
  while Remaining <> '' do
  begin
    PipePos := Pos('|', Remaining);
    if PipePos > 0 then
    begin
      Entry := Copy(Remaining, 1, PipePos - 1);
      Remaining := Copy(Remaining, PipePos + 1, Length(Remaining));
    end
    else
    begin
      Entry := Remaining;
      Remaining := '';
    end;

    EqPos := Pos('=', Entry);
    if EqPos > 0 then
    begin
      EntryName := Copy(Entry, 1, EqPos - 1);
      if EntryName = Name then
      begin
        Entry := Name + '=' + Value;
        Found := True;
      end;
    end;

    if Result <> '' then Result := Result + '|';
    Result := Result + Entry;
  end;
  if not Found then
  begin
    if Result <> '' then Result := Result + '|';
    Result := Result + Name + '=' + Value;
  end;
end;

{ --- MatchesFilter (from Generic.pas) --- }
{ Port of the pipe-separated filter parsing:                               }
{   "PropName=Value|PropName=Value" (AND logic).                          }
{ Returns 'true'/'false'.                                                  }

function MatchesFilter(PropStore : String; FilterStr : String) : String;
var
  Remaining, Condition, PropName, Expected, Actual : String;
  PipePos, EqPos : Integer;
begin
  Result := 'true';
  if FilterStr = '' then Exit;

  Remaining := FilterStr;
  while Remaining <> '' do
  begin
    PipePos := Pos('|', Remaining);
    if PipePos > 0 then
    begin
      Condition := Copy(Remaining, 1, PipePos - 1);
      Remaining := Copy(Remaining, PipePos + 1, Length(Remaining));
    end
    else
    begin
      Condition := Remaining;
      Remaining := '';
    end;

    EqPos := Pos('=', Condition);
    if EqPos = 0 then Continue;
    PropName := Copy(Condition, 1, EqPos - 1);
    Expected := Copy(Condition, EqPos + 1, Length(Condition));

    Actual := GetStoredProperty(PropStore, PropName);
    if Actual <> Expected then
    begin
      Result := 'false';
      Exit;
    end;
  end;
end;

{ --- BuildObjectJson (from Generic.pas) --- }
{ Port of comma-separated property list -> JSON object with escaped vals. }

function BuildObjectJson(PropStore : String; PropsStr : String) : String;
var
  Remaining, PropName, PropValue : String;
  CommaPos : Integer;
  First : Boolean;
begin
  Result := '{';
  First := True;
  Remaining := PropsStr;

  while Remaining <> '' do
  begin
    CommaPos := Pos(',', Remaining);
    if CommaPos > 0 then
    begin
      PropName := Copy(Remaining, 1, CommaPos - 1);
      Remaining := Copy(Remaining, CommaPos + 1, Length(Remaining));
    end
    else
    begin
      PropName := Remaining;
      Remaining := '';
    end;

    PropValue := GetStoredProperty(PropStore, PropName);

    if not First then Result := Result + ',';
    First := False;
    Result := Result + '"' + EscapeJsonString(PropName) + '":"' + EscapeJsonString(PropValue) + '"';
  end;

  Result := Result + '}';
end;

{ --- ApplySetProperties (from Generic.pas) --- }
{ Port of pipe-separated "PropName=Value" assignments. Returns modified    }
{ property store.                                                          }

function ApplySetProperties(PropStore : String; SetStr : String) : String;
var
  Remaining, Assignment, PropName, PropValue : String;
  PipePos, EqPos : Integer;
begin
  Result := PropStore;
  Remaining := SetStr;
  while Remaining <> '' do
  begin
    PipePos := Pos('|', Remaining);
    if PipePos > 0 then
    begin
      Assignment := Copy(Remaining, 1, PipePos - 1);
      Remaining := Copy(Remaining, PipePos + 1, Length(Remaining));
    end
    else
    begin
      Assignment := Remaining;
      Remaining := '';
    end;

    EqPos := Pos('=', Assignment);
    if EqPos = 0 then Continue;
    PropName := Copy(Assignment, 1, EqPos - 1);
    PropValue := Copy(Assignment, EqPos + 1, Length(Assignment));

    Result := SetStoredProperty(Result, PropName, PropValue);
  end;
end;

{ --- BatchModify operation splitting (from Gen_BatchModify) --- }
{ Parses pipe-separated operations, each "scope;object_type;filter;set",  }
{ and returns the count of VALID operations (object_type != '' and        }
{ set != ''). Mirrors the iteration/counting portion of Gen_BatchModify.  }

{ --------------------------------------------------------------------------
  NextBatchOp / GetBatchField -- copied VERBATIM from Main.pas.

  These parse the batch payload every bulk tool sends: operations split on
  '~~', fields within an operation split on ';', and key/value split on the
  FIRST '='. The Python emitters build that string, so their sanitiser has
  to match this parser exactly -- and until now that match was asserted by
  reading the Pascal, not by running it.

  What the grammar actually permits, which is the part worth pinning:
    * a value MAY contain '=' (only the first one splits)
    * a value may NOT contain ';' (it ends the field early)
    * a value may not contain '~~' (it ends the operation)
    * keys are matched case-insensitively
  -------------------------------------------------------------------------- }

function NextBatchOp(var Remaining : String) : String;
var
  SepPos : Integer;
begin
  Result := '';
  while Length(Remaining) > 0 do
  begin
    SepPos := Pos('~~', Remaining);
    if SepPos = 0 then
    begin
      Result := Remaining;
      Remaining := '';
      Exit;
    end;
    Result := Copy(Remaining, 1, SepPos - 1);
    Remaining := Copy(Remaining, SepPos + 2, Length(Remaining));
    if Result <> '' then Exit;
  end;
end;

function GetBatchField(Op : String; Key : String) : String;
var
  Remaining, Field, FKey, FVal : String;
  SepPos, EqPos : Integer;
begin
  Result := '';
  Remaining := Op;
  while Length(Remaining) > 0 do
  begin
    SepPos := Pos(';', Remaining);
    if SepPos = 0 then
    begin
      Field := Remaining;
      Remaining := '';
    end
    else
    begin
      Field := Copy(Remaining, 1, SepPos - 1);
      Remaining := Copy(Remaining, SepPos + 1, Length(Remaining));
    end;
    EqPos := Pos('=', Field);
    if EqPos > 0 then
    begin
      FKey := Copy(Field, 1, EqPos - 1);
      FVal := Copy(Field, EqPos + 1, Length(Field));
      if UpperCase(FKey) = UpperCase(Key) then
      begin
        Result := FVal;
        Exit;
      end;
    end;
  end;
end;

{ ---------------------------------------------------------------------------
  IEEE pin-symbol converters, copied VERBATIM from scripts/altium/Utils.pas.
  These decide whether an active-low pin gets its inversion bubble and a clock
  pin its wedge, and they run inside Altium where nothing can be stepped
  through. Compiling the identical source here is the only way to check the
  token-splitting logic against a real Pascal compiler.

  StrToIeeeSymbol calls StrToIntDef, which DelphiScript provides as a builtin
  and Free Pascal provides from SysUtils with the same "default on failure"
  contract, so the copy needs no shim. IsIntStr comes along because Utils.pas
  defines it and the harness did not have it.
  --------------------------------------------------------------------------- }

function IsIntStr(S : String) : Boolean;
var
  I, StartPos : Integer;
begin
  S := Trim(S);
  Result := False;
  if S = '' then Exit;
  StartPos := 1;
  if S[1] = '-' then StartPos := 2;
  if StartPos > Length(S) then Exit;   { a lone '-' is not an integer }
  for I := StartPos to Length(S) do
    if (S[I] < '0') or (S[I] > '9') then Exit;
  Result := True;
end;

function StripChar(S : String; C : Char) : String;
var
  I : Integer;
begin
  Result := '';
  for I := 1 to Length(S) do
    if S[I] <> C then Result := Result + S[I];
end;

function IeeeSymbolNames : String;
begin
  Result :=
    'no_symbol|dot|right_left_signal_flow|clock|active_low_input|' +
    'analog_signal_in|not_logic_connection|shift_right|postponed_output|' +
    'open_collector|hiz|high_current|pulse|schmitt|delay|group_line|' +
    'group_bin|active_low_output|pi_symbol|greater_equal|less_equal|' +
    'sigma|open_collector_pullup|open_emitter|open_emitter_pullup|' +
    'digital_signal_in|and|invertor|or|xor|shift_left|input_output|' +
    'open_circuit_output|left_right_signal_flow|bidirectional_signal_flow';
end;

function IeeeSymbolToStr(V : Integer) : String;
var
  Names, Tok : String;
  I, P : Integer;
begin
  Result := 'no_symbol';
  if V <= 0 then Exit;
  Names := IeeeSymbolNames + '|';
  I := 0;
  while Names <> '' do
  begin
    P := Pos('|', Names);
    if P = 0 then Break;
    Tok := Copy(Names, 1, P - 1);
    Names := Copy(Names, P + 1, Length(Names));
    if I = V then
    begin
      Result := Tok;
      Exit;
    end;
    I := I + 1;
  end;
end;

function StrToIeeeSymbol(S : String) : Integer;
var
  LS, Compact, Names, Tok : String;
  I, P : Integer;
begin
  Result := 0;
  LS := LowerCase(Trim(S));
  if LS = '' then Exit;

  if IsIntStr(LS) then
  begin
    Result := StrToIntDef(LS, 0);
    if (Result < 0) or (Result > 34) then Result := 0;
    Exit;
  end;

  Compact := StripChar(LS, '_');
  if (Compact = 'inverted') or (Compact = 'inversion') or (Compact = 'bubble')
      or (Compact = 'activelow') or (Compact = 'negated') then
  begin
    Result := 1;    { eDot }
    Exit;
  end;
  if Compact = 'clk' then
  begin
    Result := 3;    { eClock }
    Exit;
  end;

  Names := IeeeSymbolNames + '|';
  I := 0;
  while Names <> '' do
  begin
    P := Pos('|', Names);
    if P = 0 then Break;
    Tok := StripChar(Copy(Names, 1, P - 1), '_');
    Names := Copy(Names, P + 1, Length(Names));
    if Compact = Tok then
    begin
      Result := I;
      Exit;
    end;
    if (Length(Compact) > 1) and (Compact[1] = 'e') then
      if Copy(Compact, 2, Length(Compact)) = Tok then
      begin
        Result := I;
        Exit;
      end;
    I := I + 1;
  end;
end;

{ Name every ordinal 0..34 and parse the name straight back. Any disagreement
  between the two converters, or an off-by-one in the token walk, shows up as
  an ordinal that fails to survive the trip. }
function IeeeRoundTripSweep : String;
var
  I : Integer;
begin
  Result := '';
  for I := 0 to 34 do
  begin
    if I > 0 then Result := Result + '|';
    Result := Result + IntToStr(StrToIeeeSymbol(IeeeSymbolToStr(I)));
  end;
end;

{ Split a whole payload and report every op's value for one key, so a test
  can check the two parsers together rather than one at a time. }
function BatchFieldSweep(Payload : String; Key : String) : String;
var
  Remaining, Op, Value : String;
  First : Boolean;
begin
  Result := '';
  Remaining := Payload;
  First := True;
  repeat
    Op := NextBatchOp(Remaining);
    if Op = '' then Break;
    Value := GetBatchField(Op, Key);
    if not First then Result := Result + '|';
    Result := Result + Value;
    First := False;
  until Length(Remaining) = 0;
end;

function CountBatchOperations(Operations : String) : Integer;
var
  Remaining, OpStr, Scope, ObjTypeStr, FilterStr, SetStr : String;
  PipePos, SemiPos : Integer;
  OpCount : Integer;
begin
  OpCount := 0;
  Remaining := Operations;

  while Length(Remaining) > 0 do
  begin
    PipePos := Pos('|', Remaining);
    if PipePos = 0 then
    begin
      OpStr := Remaining;
      Remaining := '';
    end
    else
    begin
      OpStr := Copy(Remaining, 1, PipePos - 1);
      Remaining := Copy(Remaining, PipePos + 1, Length(Remaining));
    end;

    if OpStr = '' then Continue;

    SemiPos := Pos(';', OpStr);
    if SemiPos = 0 then Continue;
    Scope := Copy(OpStr, 1, SemiPos - 1);
    OpStr := Copy(OpStr, SemiPos + 1, Length(OpStr));

    SemiPos := Pos(';', OpStr);
    if SemiPos = 0 then Continue;
    ObjTypeStr := Copy(OpStr, 1, SemiPos - 1);
    OpStr := Copy(OpStr, SemiPos + 1, Length(OpStr));

    SemiPos := Pos(';', OpStr);
    if SemiPos = 0 then Continue;
    FilterStr := Copy(OpStr, 1, SemiPos - 1);
    SetStr := Copy(OpStr, SemiPos + 1, Length(OpStr));

    if (ObjTypeStr = '') or (SetStr = '') then Continue;

    { Silence "assigned but not used" -- these are structural checks }
    if Scope = #0 then Exit;
    if FilterStr = #0 then Exit;

    Inc(OpCount);
  end;

  Result := OpCount;
end;

{ --- Command routing split on '.' (from Dispatcher.pas) --- }
{ Returns "Category|Action" string. Action is empty if no dot.             }

function SplitCommand(Command : String) : String;
var
  Category, Action : String;
  DotPos : Integer;
begin
  DotPos := Pos('.', Command);
  if DotPos > 0 then
  begin
    Category := Copy(Command, 1, DotPos - 1);
    Action := Copy(Command, DotPos + 1, Length(Command));
  end
  else
  begin
    Category := Command;
    Action := '';
  end;
  Result := Category + '|' + Action;
end;

{ --- From Main.pas --- }

function IsWhitespaceOrColon(S : String; Idx : Integer) : Boolean;
var
  C : String;
begin
  C := Copy(S, Idx, 1);
  Result := (C = ' ') or (C = ':') or (C = #9) or (C = #10) or (C = #13);
end;

function IsDelimiter(S : String; Idx : Integer) : Boolean;
var
  C : String;
begin
  C := Copy(S, Idx, 1);
  Result := (C = '') or (C = ',') or (C = '}') or (C = ']') or (C = ' ') or (C = #9) or (C = #10) or (C = #13);
end;

{ This is the REAL ExtractJsonValue from Main.pas with proper backslash counting }
function ExtractJsonValue(Json : String; Key : String) : String;
var
  StartPos, EndPos : Integer;
  SearchKey : String;
  BraceCount : Integer;
  BackslashCount, TempPos : Integer;
begin
  Result := '';
  SearchKey := '"' + Key + '"';
  StartPos := Pos(SearchKey, Json);
  if StartPos > 0 then
  begin
    StartPos := StartPos + Length(SearchKey);
    while (StartPos <= Length(Json)) and IsWhitespaceOrColon(Json, StartPos) do
      Inc(StartPos);

    if StartPos <= Length(Json) then
    begin
      if Copy(Json, StartPos, 1) = '"' then
      begin
        Inc(StartPos);
        EndPos := StartPos;
        while (EndPos <= Length(Json)) do
        begin
          if Copy(Json, EndPos, 1) = '"' then
          begin
            BackslashCount := 0;
            TempPos := EndPos - 1;
            while (TempPos >= StartPos) and (Copy(Json, TempPos, 1) = '\') do
            begin
              Inc(BackslashCount);
              Dec(TempPos);
            end;
            if (BackslashCount mod 2) = 0 then Break;
          end;
          Inc(EndPos);
        end;
        Result := Copy(Json, StartPos, EndPos - StartPos);
      end
      else if Copy(Json, StartPos, 1) = '{' then
      begin
        EndPos := StartPos;
        BraceCount := 1;
        Inc(EndPos);
        while (EndPos <= Length(Json)) and (BraceCount > 0) do
        begin
          if Copy(Json, EndPos, 1) = '{' then Inc(BraceCount)
          else if Copy(Json, EndPos, 1) = '}' then Dec(BraceCount);
          Inc(EndPos);
        end;
        Result := Copy(Json, StartPos, EndPos - StartPos);
      end
      else
      begin
        EndPos := StartPos;
        while (EndPos <= Length(Json)) and (not IsDelimiter(Json, EndPos)) do
          Inc(EndPos);
        Result := Copy(Json, StartPos, EndPos - StartPos);
      end;
    end;
  end;
end;

function ExtractJsonArray(Json : String; Key : String) : String;
var
  StartPos, EndPos : Integer;
  SearchKey : String;
  BracketCount : Integer;
begin
  Result := '';
  SearchKey := '"' + Key + '"';
  StartPos := Pos(SearchKey, Json);
  if StartPos > 0 then
  begin
    StartPos := StartPos + Length(SearchKey);
    while (StartPos <= Length(Json)) and IsWhitespaceOrColon(Json, StartPos) do
      Inc(StartPos);

    if (StartPos <= Length(Json)) and (Copy(Json, StartPos, 1) = '[') then
    begin
      EndPos := StartPos;
      BracketCount := 1;
      Inc(EndPos);
      while (EndPos <= Length(Json)) and (BracketCount > 0) do
      begin
        if Copy(Json, EndPos, 1) = '[' then Inc(BracketCount)
        else if Copy(Json, EndPos, 1) = ']' then Dec(BracketCount);
        Inc(EndPos);
      end;
      Result := Copy(Json, StartPos, EndPos - StartPos);
    end;
  end;
end;

function BuildSuccessResponse(RequestId : String; Data : String) : String;
begin
  if Data = '' then
    Data := 'null';
  Result := '{"id":"' + RequestId + '","success":true,"data":' + Data + ',"error":null}';
end;

function BuildErrorResponse(RequestId : String; ErrorCode : String; ErrorMsg : String) : String;
begin
  ErrorMsg := StringReplace(ErrorMsg, '\', '\\', [rfReplaceAll]);
  ErrorMsg := StringReplace(ErrorMsg, '"', '\"', [rfReplaceAll]);
  ErrorMsg := StringReplace(ErrorMsg, #13, '\r', [rfReplaceAll]);
  ErrorMsg := StringReplace(ErrorMsg, #10, '\n', [rfReplaceAll]);
  ErrorMsg := StringReplace(ErrorMsg, #9, '\t', [rfReplaceAll]);
  Result := '{"id":"' + RequestId + '","success":false,"data":null,"error":{"code":"' + ErrorCode + '","message":"' + ErrorMsg + '"}}';
end;

{ ========================================================================= }
{ Dispatcher                                                                 }
{ ========================================================================= }

{ --- From Generic.pas. Kept byte-identical to the original;   }
{ tests/test_pin_connection_point.py fails if they diverge.    }
Function PinEndX(RootX : Integer; Orient : Integer; PinLen : Integer) : Integer;
Begin
    Result := RootX;
    If Orient = 0 Then Result := RootX + PinLen
    Else If Orient = 2 Then Result := RootX - PinLen;
End;

Function PinEndY(RootY : Integer; Orient : Integer; PinLen : Integer) : Integer;
Begin
    Result := RootY;
    If Orient = 1 Then Result := RootY + PinLen
    Else If Orient = 3 Then Result := RootY - PinLen;
End;

{ --- From Dispatcher.pas. Kept byte-identical to the original; }
{ tests/test_netlist_cache_staleness.py fails if they diverge.  }
Function ActionHasPrefix(Verb : String; Prefix : String) : Boolean;
Begin
    Result := Copy(Verb, 1, Length(Prefix)) = Prefix;
End;

Function CommandIsReadOnly(Command : String) : Boolean;
Var
    Verb : String;
    DotPos : Integer;
Begin
    Verb := LowerCase(Trim(Command));
    DotPos := Pos('.', Verb);
    If DotPos > 0 Then Verb := Copy(Verb, DotPos + 1, Length(Verb) - DotPos);

    Result := ActionHasPrefix(Verb, 'get_')
           Or ActionHasPrefix(Verb, 'list_')
           Or ActionHasPrefix(Verb, 'query')
           Or ActionHasPrefix(Verb, 'read_')
           Or ActionHasPrefix(Verb, 'find_')
           Or ActionHasPrefix(Verb, 'count')
           Or ActionHasPrefix(Verb, 'audit_')
           Or ActionHasPrefix(Verb, 'check_')
           Or ActionHasPrefix(Verb, 'calc_')
           Or ActionHasPrefix(Verb, 'export_')
           Or ActionHasPrefix(Verb, 'render_')
           Or ActionHasPrefix(Verb, 'probe_')
           Or ActionHasPrefix(Verb, 'inspect_')
           Or ActionHasPrefix(Verb, 'diff_')
           Or ActionHasPrefix(Verb, 'compare_')
           Or (Verb = 'ping');
End;

function B64Decode(S : String) : String;
begin
  { Convention: '_' means empty string (avoids empty base64 fields) }
  if (S = '') or (S = '_') then
    Result := ''
  else
    Result := DecodeStringBase64(S);
end;

function B64Encode(S : String) : String;
begin
  { Convention: '_' means empty string (avoids empty base64 output lines) }
  if S = '' then
    Result := '_'
  else
    Result := EncodeStringBase64(S);
end;

procedure ProcessLine(Line : String; var OutFile : TextFile);
var
  Parts : TStringList;
  FnName : String;
  ResultStr : String;
  IntResult : Integer;
  FloatResult : Double;
  BoolResult : Boolean;
  SavedSep : Char;
begin
  Parts := TStringList.Create;
  try
    Parts.Delimiter := #9;
    Parts.StrictDelimiter := True;
    Parts.DelimitedText := Line;

    if Parts.Count < 1 then Exit;
    FnName := Parts[0];
    ResultStr := '';

    { --- FloatUnderComma: emit then parse with a comma separator --- }
    if FnName = 'FloatUnderComma' then
    begin
      SavedSep := DecimalSeparator;
      DecimalSeparator := ',';
      try
        ResultStr := FloatToJsonStr(StrToFloat(StringReplace(
          B64Decode(Parts[1]), '.', ',', [rfReplaceAll])));
      finally
        DecimalSeparator := SavedSep;
      end;
    end

    { --- ParseUnderComma: parse a dot-form string on a comma locale --- }
    else if FnName = 'ParseUnderComma' then
    begin
      SavedSep := DecimalSeparator;
      DecimalSeparator := ',';
      try
        FloatResult := StrToFloatDef(B64Decode(Parts[1]), -999);
        ResultStr := FloatToJsonStr(FloatResult);
      finally
        DecimalSeparator := SavedSep;
      end;
    end

    { --- PinEndX: args = root_x, orient, pin_len --- }
    else if FnName = 'PinEndX' then
    begin
      ResultStr := IntToStr(PinEndX(StrToInt(B64Decode(Parts[1])),
                                    StrToInt(B64Decode(Parts[2])),
                                    StrToInt(B64Decode(Parts[3]))));
    end

    { --- PinEndY: args = root_y, orient, pin_len --- }
    else if FnName = 'PinEndY' then
    begin
      ResultStr := IntToStr(PinEndY(StrToInt(B64Decode(Parts[1])),
                                    StrToInt(B64Decode(Parts[2])),
                                    StrToInt(B64Decode(Parts[3]))));
    end

    { --- CommandIsReadOnly: args = command --- }
    else if FnName = 'CommandIsReadOnly' then
    begin
      if CommandIsReadOnly(B64Decode(Parts[1])) then
        ResultStr := 'true'
      else
        ResultStr := 'false';
    end

    { --- ExtractJsonValue: args = json_str, key --- }
    else if FnName = 'ExtractJsonValue' then
    begin
      ResultStr := ExtractJsonValue(B64Decode(Parts[1]), B64Decode(Parts[2]));
    end

    { --- ExtractJsonArray: args = json_str, key --- }
    else if FnName = 'ExtractJsonArray' then
    begin
      ResultStr := ExtractJsonArray(B64Decode(Parts[1]), B64Decode(Parts[2]));
    end

    { --- GetBatchField: args = op, key --- }
    else if FnName = 'GetBatchField' then
    begin
      ResultStr := GetBatchField(B64Decode(Parts[1]), B64Decode(Parts[2]));
    end

    { --- BatchFieldSweep: args = payload, key --- }
    else if FnName = 'BatchFieldSweep' then
    begin
      ResultStr := BatchFieldSweep(B64Decode(Parts[1]), B64Decode(Parts[2]));
    end

    { --- StrToIeeeSymbol: args = s --- }
    else if FnName = 'StrToIeeeSymbol' then
    begin
      ResultStr := IntToStr(StrToIeeeSymbol(B64Decode(Parts[1])));
    end

    { --- IeeeSymbolToStr: args = ordinal (int) --- }
    else if FnName = 'IeeeSymbolToStr' then
    begin
      ResultStr := IeeeSymbolToStr(StrToInt(B64Decode(Parts[1])));
    end

    { --- IeeeRoundTripSweep: no args --- }
    else if FnName = 'IeeeRoundTripSweep' then
    begin
      ResultStr := IeeeRoundTripSweep;
    end

    { --- EscapeJsonString: args = s --- }
    else if FnName = 'EscapeJsonString' then
    begin
      ResultStr := EscapeJsonString(B64Decode(Parts[1]));
    end

    { --- BuildSuccessResponse: args = request_id, data --- }
    else if FnName = 'BuildSuccessResponse' then
    begin
      ResultStr := BuildSuccessResponse(B64Decode(Parts[1]), B64Decode(Parts[2]));
    end

    { --- BuildErrorResponse: args = request_id, error_code, error_msg --- }
    else if FnName = 'BuildErrorResponse' then
    begin
      ResultStr := BuildErrorResponse(B64Decode(Parts[1]), B64Decode(Parts[2]), B64Decode(Parts[3]));
    end

    { --- MilsToCoord: args = mils (int) --- }
    else if FnName = 'MilsToCoord' then
    begin
      IntResult := MilsToCoord(StrToInt(B64Decode(Parts[1])));
      ResultStr := IntToStr(IntResult);
    end

    { --- CoordToMils: args = coord (int) --- }
    else if FnName = 'CoordToMils' then
    begin
      IntResult := CoordToMils(StrToInt(B64Decode(Parts[1])));
      ResultStr := IntToStr(IntResult);
    end

    { --- MMToCoord: args = mm (float) --- }
    else if FnName = 'MMToCoord' then
    begin
      FloatResult := StrToFloat(B64Decode(Parts[1]));
      IntResult := MMToCoord(FloatResult);
      ResultStr := IntToStr(IntResult);
    end

    { --- CoordToMM: args = coord (int) --- }
    else if FnName = 'CoordToMM' then
    begin
      FloatResult := CoordToMM(StrToInt(B64Decode(Parts[1])));
      { Use enough decimal places to distinguish, match Python formatting }
      ResultStr := FormatFloat('0.0000000000', FloatResult);
    end

    { --- StrToIntDef: args = s, default (int) --- }
    else if FnName = 'StrToIntDef' then
    begin
      IntResult := StrToIntDefCustom(B64Decode(Parts[1]), StrToInt(B64Decode(Parts[2])));
      ResultStr := IntToStr(IntResult);
    end

    { --- StrToFloatDef: args = s, default (float) --- }
    else if FnName = 'StrToFloatDef' then
    begin
      FloatResult := StrToFloatDef(B64Decode(Parts[1]), StrToFloat(B64Decode(Parts[2])));
      ResultStr := FormatFloat('0.0000000000', FloatResult);
    end

    { --- BoolToJsonStr: args = bool_str ("true"/"false") --- }
    else if FnName = 'BoolToJsonStr' then
    begin
      BoolResult := (LowerCase(B64Decode(Parts[1])) = 'true');
      ResultStr := BoolToJsonStr(BoolResult);
    end

    { --- StrToBool: args = s --- }
    else if FnName = 'StrToBool' then
    begin
      BoolResult := StrToBoolCustom(B64Decode(Parts[1]));
      if BoolResult then
        ResultStr := 'true'
      else
        ResultStr := 'false';
    end

    { --- MatchesFilter: args = prop_store, filter_str --- }
    else if FnName = 'MatchesFilter' then
    begin
      ResultStr := MatchesFilter(B64Decode(Parts[1]), B64Decode(Parts[2]));
    end

    { --- BuildObjectJson: args = prop_store, props_str --- }
    else if FnName = 'BuildObjectJson' then
    begin
      ResultStr := BuildObjectJson(B64Decode(Parts[1]), B64Decode(Parts[2]));
    end

    { --- ApplySetProperties: args = prop_store, set_str --- }
    else if FnName = 'ApplySetProperties' then
    begin
      ResultStr := ApplySetProperties(B64Decode(Parts[1]), B64Decode(Parts[2]));
    end

    { --- CountBatchOperations: args = operations_str --- }
    else if FnName = 'CountBatchOperations' then
    begin
      IntResult := CountBatchOperations(B64Decode(Parts[1]));
      ResultStr := IntToStr(IntResult);
    end

    { --- SplitCommand: args = command_str --- }
    else if FnName = 'SplitCommand' then
    begin
      ResultStr := SplitCommand(B64Decode(Parts[1]));
    end

    else
    begin
      ResultStr := 'ERROR:UNKNOWN_FUNCTION:' + FnName;
    end;

    WriteLn(OutFile, B64Encode(ResultStr));
  finally
    Parts.Free;
  end;
end;

{ ========================================================================= }
{ Main                                                                       }
{ ========================================================================= }

var
  InputPath, OutputPath : String;
  InFile, OutFile : TextFile;
  Line : String;
  LineCount : Integer;

begin
  { Set decimal separator to '.' for consistent float formatting }
  {$IFDEF FPC}
  DefaultFormatSettings.DecimalSeparator := '.';
  {$ENDIF}

  if ParamCount < 2 then
  begin
    WriteLn('Usage: cross_validate_pascal.exe <input_file> <output_file>');
    Halt(1);
  end;

  InputPath := ParamStr(1);
  OutputPath := ParamStr(2);

  if not FileExists(InputPath) then
  begin
    WriteLn('Error: input file not found: ', InputPath);
    Halt(1);
  end;

  AssignFile(InFile, InputPath);
  Reset(InFile);

  AssignFile(OutFile, OutputPath);
  Rewrite(OutFile);

  LineCount := 0;
  try
    while not EOF(InFile) do
    begin
      ReadLn(InFile, Line);
      if Length(Line) > 0 then
      begin
        ProcessLine(Line, OutFile);
        Inc(LineCount);
      end;
    end;
  finally
    CloseFile(InFile);
    CloseFile(OutFile);
  end;

  WriteLn('Processed ', LineCount, ' test cases.');
end.
